
imports:
    - { resource: eight_points_guzzle.yaml }

services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  thirdparts.agora.api:
    class: ThirdParts\AgoraBundle\Service\Api\AgoraApi
    arguments:
      - '@eight_points_guzzle.client.crm'
      - '@monolog.logger.security'
